package wow

var data = []string{
	"The best way out is always through.",
	"Seize the moment.",
	"Always Do What You Are Afraid To Do.",
	"Believe and act as if it were impossible to fail.",
	"Keep steadily before you the fact that all true success depends at last upon yourself.",
	"The journey of a thousand miles begins with one step.",
	"Opportunity is always knocking. The problem is that most people have the self-doubt station in their heads turned up way too loud to hear it.",
	"You must be the change you wish to see in the world.",
	"Tough times never last, but tough people do.",
	"You must not only aim right, but draw the bow with all your might.",
	"Everyone has inside them a piece of good news. The good news is you don’t know how great you can be! How much you can love! What you can accomplish! And what your potential is.",
	"Soon, when all is well, you’re going to look back on this period of your life and be so glad that you never gave up.",
	"You must never be fearful about what you are doing when it is right.",
	"Strive not to be a success but rather to be of value.",
	"The best revenge is massive success.",
	"It is time for us all to stand and cheer for the doer, the achiever – the one who recognizes the challenges and does something about it.",
	"The harder the conflict, the more glorious the triumph.",
	"The first step toward success is taken when you refuse to be a captive of the environment in which you first find yourself.",
	"Always do your best. What you plant now, you will harvest later.",
	"Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.",
	"When it is obvious that the goals cannot be reached, don’t adjust the goals, adjust the action steps.",
	"You can never plan the future by the past.",
	"He who has a why to live can bear almost any how.",
	"Lost time is never found again.",
	"In three words I can sum up everything I’ve learned about life: it goes on.",
	"In the end, it’s not the years in your life that count. It’s the life in your years.",
	"The greatest day in your life and mine is when we take total responsibility for our attitudes. That’s the day we truly grow up.",
	"My mission in life is not merely to survive, but to thrive; and to do so with some passion, some compassion, some humor, and some style.",
	"What we think determines what happens to us, so if we want to change our lives, we need to stretch our minds.",
	"Life is either a daring adventure or nothing at all.",
	"Believe that life is worth living and your belief will help create the fact.",
	"I’m always doing things I can’t do. That’s how I get to do them.",
	"There are three constants in life…change, choice and principles.",
	"It is better to be hated for what you are than to be loved for what you are not.",
	"We make a living by what we get, but we make a life by what we give.",
	"Do not take life too seriously. You will never get out of it alive.",
	"Life is not a problem to be solved, but a reality to be experienced.",
	"It always seems impossible until it’s done.",
	"Life is ten percent what happens to you and ninety percent how you respond to it.",
	"Go confidently in the direction of your dreams! Live the life you’ve imagined.",
	"There is more to life than increasing its speed.",
	"The difference between the impossible and the possible lies in a man’s determination.",
	"Change is the law of life. And those who look only to the past or present are certain to miss the future.",
	"No one can compete with you on being you. Most of life is a search for who and what needs you the most.",
	"If you don’t design your own life plan, chances are you’ll fall into someone else’s plan. And guess what they have planned for you? Not much.",
	"Work hard, be kind, and amazing things will happen.",
	"The most common way people give up their power is by thinking they don’t have any.",
	"“No” simply means begin again at one level higher.",
	"Everything you’ve ever wanted is on the other side of fear.",
	"Do what you have to do until you can do what you want to do.",
	"Press forward. Do not stop, do not linger in your journey, but strive for the mark set before you.",
	"Show the world how much you’ll fight for the winners circle.",
	"It is during our darkest moments that we must focus to see the light.",
	"Do not wait to strike till the iron is hot. Make it hot by striking.",
	"If you hear a voice within you say ‘you cannot paint,’ then by all means paint and that voice will be silenced.",
	"Everybody is a genius. But if you judge a fish by its ability to climb a tree, it will live its whole life believing that it is stupid.",
	"Don’t compromise yourself. You are all you’ve got. There is no yesterday, no tomorrow, it’s all the same day.",
	"A life spent making mistakes is not only more honorable, but more useful than a life spent doing nothing.",
	"If you have knowledge, let others light their candles in it.",
	"He who fears he will suffer, already suffers because he fears.",
	"Forget about the fast lane. If you really want to fly, just harness your power to your passion.",
	"Life is really simple, but we insist on making it complicated.",
	"The opinion which other people have of you is their problem, not yours.",
	"If you don’t like something, change it. If you can’t change it, change the way you think about it.",
	"You are more powerful than you know; you are beautiful just as you are.",
	"The only way to achieve the impossible is to believe it is possible.",
	"You’ve got to get up every morning with determination if you’re going to go to bed with satisfaction.",
	"Man is only truly great when he acts from the passions; never irresistible but when he appeals to the imagination.",
	"Go as far as you can see; when you get there, you’ll be able to see further.",
	"When we strive to become better than we are, everything around us becomes better too.",
	"The individual who says it is not possible should move out of the way of those doing it.",
	"We must believe that we are gifted for something and that this thing must be attained.",
	"Build your own dreams or someone else will hire you to build theirs.",
	"Sometimes the fall kills you. And sometimes, when you fall, you fly.",
	"Never give up on a dream just because of the time it will take to accomplish it. The time will pass anyway.",
	"Learn to light a candle in the darkest moments of someone’s life. Be the light that helps others see; it is what gives life its deepest significance.",
	"I believe in only one thing, the power of human will.",
	"Laughter is poison to fear.",
	"A wise warrior learns from her mistakes.",
	"Begin, be bold, and venture to be wise.",
	"The well-bred contradict other people. the wise contradict themselves.",
	"I don’t fancy colors of the face, I’m always attracted to colors of the brain.",
	"I don’t agree that when you love, you are blind or fool. You just get wiser and see clearer what is best and of worth.",
	"Like a missing tooth, sometimes an absence is more noticeable than a presence.",
	"Love the people who love you back.",
	"It’s the questions we can’t answer that teach us the most. They teach us how to think. If you give a man an answer, all he gains is a little fact. But give him a question and he’ll look for his own answers.",
	"Whatever choice you make makes you. Choose wisely.",
	"Dieting is the only game where you win when you lose!",
	"No matter how tiny you look, you can lead huge men if you have what the huge men don’t have.",
	"I criticize by creation, not by finding fault.",
	"Faith keeps our ships moving, while empathy and the memories of our experiences lead to wisdom.",
	"The wisest men follow their own direction.",
	"Make your lives a masterpiece, you only get one canvas.",
	"The weak are dominated by their ego, the wise dominate their ego, and the intelligent are in a constant struggle against their ego.",
	"The choice to make good choices is the best choice you can choose. Fail to make that choice and on most choices you will lose.",
	"Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
	"Circumstances are the rulers of the weak; they are but the instruments of the wise.",
	"Letting go means to come to the realization that some people are a part of your history, but not a part of your destiny.",
	"Action may not always bring happiness, but there is no happiness without action.",
	"The man who moves a mountain begins by carrying away small stones.",
	"You have to accept whatever comes, and the only important thing is that you meet it with the best you have to give.",
	"Without ambition one starts nothing. Without work one finishes nothing. The prize will not be sent to you. You have to win it.",
	"In the end, you have to choose whether or not to trust someone.",
	"Learn the rules like a pro, so you can break them like an artist.",
	"Don’t fear failure. — Not failure, but low aim, is the crime. In great attempts it is glorious even to fail.",
	"Pursue what catches your heart, not what catches your eyes.",
	"Whatever the mind can conceive and believe, it can achieve.",
	"Lack of direction, not lack of time, is the problem. We all have twenty-four hour days.",
	"You are the average of the five people you spend the most time with.",
	"The only way of discovering the limits of the possible is to venture a little way past them into the impossible.",
	"Only he who attempts the absurd is capable of achieving the impossible.",
	"Change the way you look at things and the things you look at change.",
	"Don’t wish it were easier. Wish you were better.",
	"Although the world is full of suffering, it is full also of the overcoming of it.",
	"I cannot let the fear of the past color the future.",
	"Common sense is genius dressed in its working clothes.",
	"Don’t settle for what life gives you; make life better and build something.",
	"You never really learn much from hearing yourself speak.",
	"Too many of us are not living our dreams because we are living our fears.",
	"The best way to predict your future is to create it.",
	"We generate fears while we sit. We overcome them by action.",
	"Enjoy your sweat because hard work doesn’t guarantee success, but without it, you don’t have a chance.",
	"Success depends upon previous preparation, and without such preparation, there is sure to be failure.",
	"Opportunities don’t happen. You create them.",
	"Motivation is what gets you started. Habit is what keeps you going.",
	"Rarely have I seen a situation where doing less than the other guy is a good strategy.",
	"Only put off until tomorrow what you are willing to die having left undone.",
	"If you look at what you have in life, you’ll always have more. If you look at what you don’t have in life, you’ll never have enough.",
	"Do what you can with all you have, wherever you are.",
	"What seems to us as bitter trials are often blessings in disguise.",
	"Play to your strengths. If you aren’t great at something, do more of what you’re great at.",
	"Change before you have to.",
	"Everyone thinks of changing the world, but no one thinks of changing himself.",
	"Since we cannot change reality, let us change the eyes which see reality.",
	"To improve is to change; to be perfect is to change often.",
	"The measure of intelligence is the ability to change.",
	"The secret of change is to focus all of your energy not on fighting the old, but on building the new.",
	"I alone cannot change the world, but I can cast a stone across the waters to create many ripples.",
	"There is nothing permanent except change.",
	"Change is inevitable. Growth is optional.",
	"Do what is right, not what is easy nor what is popular.",
	"The only thing worse than being blind is having sight but no vision.",
	"Start where you are. Use what you have. Do what you can.",
	"Do one thing every day that scares you.",
	"By changing nothing, nothing changes.",
	"We are all in the gutter, but some of us are looking at the stars.",
	"You can, you should, and if you’re brave enough to start, you will.",
	"Your big opportunity may be right where you are standing right now.",
	"For every minute you are angry, you lose sixty seconds of happiness.",
	"There are far better things ahead than any we leave behind.",
	"Optimism is the one quality more associated with success and happiness than any other.",
	"It is our attitude at the beginning of a difficult task which, more than anything else, will affect its successful outcome.",
	"People who are crazy enough to think they can change the world, are the ones who do.",
	"We must be willing to let go of the life we planned so as to have the life that is waiting for us.",
	"Happiness is not something ready-made. It comes from your own actions.",
	"Happiness is not by chance, but by choice.",
	"All our dreams can come true if we have the courage to pursue them.",
	"If I cannot do great things, I can do small things in a great way.",
	"I can’t change the direction of the wind, but I can adjust my sails to always reach my destination.",
	"The only limit to our realization of tomorrow will be our doubts of today.",
	"Spread love everywhere you go.",
	"Out of the mountain of despair, a stone of hope.",
	"Nothing is impossible. The word itself says ‘I’m possible!’",
	"When you have a dream, you’ve got to grab it and never let go.",
	"The bad news is time flies. The good news is you’re the pilot.",
	"You define your own life. Don’t let other people write your script.",
	"You are never too old to set another goal or to dream a new dream.",
	"You can be everything. You can be the infinite amount of things that people are.",
	"Keep your face always toward the sunshine, and shadows will fall behind you.",
	"Do not allow people to dim your shine because they are blinded. Tell them to put some sunglasses on.",
}
